name: Selenide Testing

on:
  workflow_dispatch:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code(Load repo code into virtual machine)
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker
          

      - name: Download and set up Selenoid browsers
        run: |
          mkdir -p $HOME/.aerokube/selenoid
          cat <<EOF > $HOME/.aerokube/selenoid/browsers.json
          {
            "chrome": {
              "default": "100.0",
              "versions": {
                "100.0": {
                  "image": "selenoid/chrome:100.0",
                  "port": "4444",
                  "path": "/",
                  "tmpfs": { "/tmp": "size=512m" },
                  "env": ["LANG=C.UTF-8"],
                  "capabilities": {
                    "goog:chromeOptions": {
                      "args": ["--disable-gpu", "--no-sandbox", "--disable-dev-shm-usage", "--remote-debugging-port=9222", "--headless"]
                    }
                  }
                }
              }
            }
          }
          EOF
          docker pull selenoid/chrome:latest
          docker pull selenoid/firefox:latest

      - name: Start Selenoid
        run: |
          docker run -d --name selenoid \
            -p 4444:4444 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.aerokube/selenoid:/etc/selenoid:ro \
            aerokube/selenoid:latest-release \
            --limit 5 \
            --timeout 1m \
            --video-output-dir /opt/selenoid/video
          
      - name: Verify Selenoid is running
        run: curl -s http://localhost:4444/status | jq

      - name: Run Selenide Tests
        run: mvn clean test
        env:
          SELENOID_URL: http://localhost:4444/wd/hub