name: Selenide Testing

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code(Load repo code into virtual machine)
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Selenide Tests
        run: mvn clean test


      - name: Generate Allure Report
        run: mvn allure:report  # This generates the report in the 'target/allure-results' folder

      - name: Upload Allure Results as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results  # This uploads the raw allure result files for later inspection

      - name: Serve Allure Report
        run: |
          allure serve target/allure-results  # This will generate and serve the report
        continue-on-error: true  # This ensures that the job doesn't fail if serving the report fails